name: Django CI

on:
  push:
    branches:
      - main  # Run workflow on push to the main branch
  pull_request:
    branches:
      - main  # Run workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Django 5.1 requires Python 3.11 or higher

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Django migrations
      - name: Apply database migrations
        run: python manage.py migrate

      # Optional: Step 5 - Debugging step for version checks
      - name: Verify Python and Django versions
        run: |
          python --version
          python -m django --version
